name: Test

on:
  pull_request:
    types : ["opened", "edited", "reopened"]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest


    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test
        run: |
         echo ${{github.event.pull_request.number}}
         echo ${{github.event.pull_request.base}}




