name: Test

on:
  pull_request:
    types : ["opened", "edited", "reopened"]



jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run script
        run: echo $github.event.number


