name: Test

on:
  pull_request:
    types : ["opened", "edited", "reopened"]



jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: PR Branch Labeler
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}




